image: python:3.6-alpine

pages:
  stage: deploy
  before_script:
  - python -m pip install -r requirements.txt
  script:
  - cd public/
  - python render.py
  - cd ..
  artifacts:
    paths:
    - public
  only:
  - master
